export const sections = [
  { title: 'Grundlage & Orientierung', kicker: 'Scope before score', checks: [
    { id: 'title', level: 'A', wcag: '2.4.2', title: 'Hat jede Seite einen eindeutigen Seitentitel?', summary: 'Der Titel beschreibt Inhalt oder Zweck und unterscheidet ähnliche Seiten.', test: 'Prüfe den Browser-Tab auf mehreren Seitentypen. Der spezifische Seitenname sollte vor einem wiederkehrenden Organisationsnamen stehen.' },
    { id: 'language', level: 'A', wcag: '3.1.1 / 3.1.2', title: 'Sind Hauptsprache und Sprachwechsel ausgezeichnet?', summary: 'Screenreader können Aussprache und Sprachregeln korrekt wählen.', test: 'Kontrolliere lang am html-Element und abweichende Sprachen an einzelnen Textpassagen. Eigennamen und gebräuchliche Fremdwörter brauchen nicht immer einen Wechsel.' },
    { id: 'landmarks', level: 'A', wcag: '1.3.1 / 2.4.1', title: 'Sind Seitenbereiche semantisch gegliedert?', summary: 'Header, Navigation, Hauptinhalt und Footer sind programmatisch erkennbar.', test: 'Prüfe Landmarken im Accessibility-Tree oder mit einem Screenreader. Es sollte genau einen klaren Hauptinhalt geben.' },
    { id: 'bypass', level: 'A', wcag: '2.4.1', title: 'Kann wiederkehrender Inhalt übersprungen werden?', summary: 'Ein funktionierender Skip-Link oder gleichwertiger Mechanismus führt zum Hauptinhalt.', test: 'Lade die Seite neu und drücke Tab. Der Skip-Link muss sichtbar werden, aktivierbar sein und den Fokus sinnvoll versetzen.' },
    { id: 'consistent-nav', level: 'AA', wcag: '3.2.3 / 3.2.4', title: 'Bleiben Navigation und Bezeichnungen konsistent?', summary: 'Wiederkehrende Komponenten erscheinen in ähnlicher Reihenfolge und heißen gleich.', test: 'Vergleiche mehrere Seiten. Gleiche Funktionen sollten nicht wechselnd benannt oder überraschend anders platziert sein.' },
    { id: 'multiple-ways', level: 'AA', wcag: '2.4.5', title: 'Sind Seiten auf mehr als einem Weg auffindbar?', summary: 'Neben der Navigation gibt es beispielsweise Suche, Sitemap oder eine passende Übersicht.', test: 'Prüfe, ob Inhaltsseiten über mindestens zwei Wege erreichbar sind. Seiten innerhalb eines linearen Prozesses dürfen davon ausgenommen sein.' },
    { id: 'help', level: 'A', wcag: '3.2.6', title: 'Ist angebotene Hilfe konsistent auffindbar?', summary: 'Kontakt-, Support- oder Selbsthilfeoptionen stehen auf Seiten in gleicher relativer Reihenfolge.', test: 'Prüfe wiederkehrende Hilfemechanismen auf mehreren Seiten eines Prozesses. Nicht jede Website muss Hilfe anbieten.' }
  ]},
  { title: 'Wahrnehmung & Gestaltung', kicker: 'Readable by design', checks: [
    { id: 'color-only', level: 'A', wcag: '1.4.1', title: 'Werden Informationen nicht nur über Farbe vermittelt?', summary: 'Status, Fehler und Auswahl besitzen zusätzlich Text, Form, Icon oder Muster.', test: 'Betrachte die Seite in Graustufen. Bedeutung und Interaktionszustände müssen weiterhin verständlich sein.' },
    { id: 'text-contrast', level: 'AA', wcag: '1.4.3', title: 'Erreichen Texte die nötigen Kontraste?', summary: 'Normaler Text mindestens 4,5:1, großer Text mindestens 3:1.', test: 'Messe Vorder- und Hintergrundfarbe in allen Zuständen. Groß bedeutet mindestens 24 CSS-px normal oder etwa 18,7 CSS-px fett.', tip: 'Verlasse dich nicht auf die visuelle Einschätzung. Transparenz, Verläufe und wechselnde Bildhintergründe müssen mitgemessen werden.' },
    { id: 'ui-contrast', level: 'AA', wcag: '1.4.11', title: 'Sind Bedienelemente und relevante Grafiken ausreichend kontrastreich?', summary: 'Erforderliche Grenzen, Icons, Fokusindikatoren und Diagrammteile erreichen mindestens 3:1.', test: 'Prüfe Komponenten gegen angrenzende Farben – einschließlich Hover, Fokus, Auswahl und Fehlerzustand.' },
    { id: 'resize', level: 'AA', wcag: '1.4.4', title: 'Bleibt Inhalt bei 200 % Textvergrößerung nutzbar?', summary: 'Text kann ohne Informations- oder Funktionsverlust vergrößert werden.', test: 'Vergrößere nur den Text auf 200 %. Prüfe Überlagerungen, abgeschnittene Beschriftungen und unerreichbare Funktionen.' },
    { id: 'reflow', level: 'AA', wcag: '1.4.10', title: 'Funktioniert die Seite bei schmalem Viewport ohne zweidimensionales Scrollen?', summary: 'Bei 320 CSS-px Breite bleibt der Inhalt grundsätzlich in einer Richtung lesbar.', test: 'Teste bei 1280 CSS-px Breite mit 400 % Zoom oder direkt bei 320 CSS-px. Ausnahmen gelten etwa für große Tabellen oder Karten.' },
    { id: 'text-spacing', level: 'AA', wcag: '1.4.12', title: 'Verträgt das Layout vergrößerte Textabstände?', summary: 'Angepasste Zeilen-, Absatz-, Wort- und Zeichenabstände verursachen keinen Verlust.', test: 'Setze die WCAG-Testwerte per Bookmarklet oder Stylesheet und prüfe, ob Text abgeschnitten oder überlagert wird.' },
    { id: 'hover-content', level: 'AA', wcag: '1.4.13', title: 'Ist zusätzlicher Hover- oder Fokusinhalt kontrollierbar?', summary: 'Tooltips und Popover sind schließbar, mit dem Zeiger erreichbar und bleiben verfügbar.', test: 'Öffne Zusatzinhalt per Maus und Tastatur. Er darf beim Bewegen zum Inhalt nicht verschwinden und muss meist mit Escape schließbar sein.' },
    { id: 'orientation', level: 'AA', wcag: '1.3.4', title: 'Ist die Nutzung nicht unnötig auf eine Ausrichtung beschränkt?', summary: 'Inhalte funktionieren in Hoch- und Querformat, sofern eine Ausrichtung nicht wesentlich ist.', test: 'Drehe ein Mobilgerät oder simuliere beide Ausrichtungen. Fachlich notwendige Ausnahmen sind möglich.' }
  ]},
  { title: 'Inhalt & Struktur', kicker: 'Meaning before markup', checks: [
    { id: 'headings', level: 'A/AA', wcag: '1.3.1 / 2.4.6', title: 'Bilden Überschriften eine verständliche Struktur?', summary: 'Echte Überschriften benennen Abschnitte; Ebenen folgen der inhaltlichen Hierarchie.', test: 'Erzeuge eine Überschriftenliste. Sie muss als Inhaltsverzeichnis verständlich sein; optisch hervorgehobener Text darf keine unechte Überschrift bleiben.' },
    { id: 'semantic-html', level: 'A', wcag: '1.3.1', title: 'Werden passende HTML-Elemente verwendet?', summary: 'Listen, Tabellen, Zitate, Buttons und Formulare vermitteln ihre Beziehungen programmatisch.', test: 'Prüfe den Accessibility-Tree. Verwende native Elemente, bevor du Rollen und Tastaturverhalten selbst nachbaust.', tip: 'ARIA ergänzt HTML, repariert aber keine falsche Semantik oder fehlende Tastaturinteraktion.' },
    { id: 'reading-order', level: 'A', wcag: '1.3.2', title: 'Ist die Lese- und Fokusreihenfolge sinnvoll?', summary: 'CSS-Positionierung verändert die Bedeutung nicht gegenüber der DOM-Reihenfolge.', test: 'Lies die Seite ohne CSS und navigiere per Tab. Visuelle, programmatische und logische Reihenfolge müssen zusammenpassen.' },
    { id: 'sensory', level: 'A', wcag: '1.3.3', title: 'Vermeiden Anweisungen rein sensorische Merkmale?', summary: 'Hinweise beruhen nicht allein auf Position, Form, Größe, Klang oder Richtung.', test: 'Suche Formulierungen wie „rechts“, „roter Button“ oder „nach dem Ton“. Ergänze einen eindeutigen Namen oder Kontext.' },
    { id: 'alt-text', level: 'A', wcag: '1.1.1', title: 'Haben informative Bilder passende Textalternativen?', summary: 'Der Alternativtext vermittelt Zweck und relevante Information im jeweiligen Kontext.', test: 'Blende Bilder aus und lies Alternativtexte. Dekorative Bilder erhalten alt=""; komplexe Grafiken brauchen zusätzlich eine ausführliche Beschreibung.', tip: 'Nicht jedes Bild braucht eine Beschreibung. Redundante Dateinamen oder „Bild von“ erzeugen eher Barrieren.' },
    { id: 'images-text', level: 'AA', wcag: '1.4.5', title: 'Wird echter Text statt Textgrafik verwendet?', summary: 'Text bleibt skalierbar, anpassbar und für assistive Technik verfügbar.', test: 'Prüfe Banner, Teaser und Buttons. Logos sowie technisch wesentliche Darstellungen können Ausnahmen sein.' },
    { id: 'tables', level: 'A', wcag: '1.3.1', title: 'Sind Datentabellen korrekt ausgezeichnet?', summary: 'Kopfzellen und ihre Bezüge sind erkennbar; Layout wird nicht mit Tabellen gebaut.', test: 'Navigiere mit einem Screenreader durch komplexe Tabellen. Verwende th und bei Bedarf scope oder headers/id sowie eine Beschriftung.' }
  ]},
  { title: 'Tastatur & Interaktion', kicker: 'No mouse required', checks: [
    { id: 'keyboard', level: 'A', wcag: '2.1.1', title: 'Ist jede Funktion per Tastatur bedienbar?', summary: 'Alle Aktionen sind ohne Maus erreichbar und ausführbar.', test: 'Nutze nur Tab, Shift+Tab, Enter, Leertaste, Pfeiltasten und Escape. Teste auch Menüs, Dialoge, Slider und Uploads.' },
    { id: 'keyboard-trap', level: 'A', wcag: '2.1.2', title: 'Kann der Tastaturfokus jede Komponente wieder verlassen?', summary: 'Es gibt keine Tastaturfalle; besondere Bedienwege werden erklärt.', test: 'Navigiere vorwärts und rückwärts durch eingebettete Inhalte und Dialoge. Ein Modal darf den Fokus nur bis zum Schließen begrenzen.' },
    { id: 'character-shortcuts', level: 'A', wcag: '2.1.4', title: 'Sind Ein-Tasten-Kurzbefehle abschaltbar oder anpassbar?', summary: 'Kurzbefehle mit Buchstaben, Zahlen oder Satzzeichen lösen bei Spracheingabe nichts versehentlich aus.', test: 'Prüfe Web-Apps auf Befehle ohne Modifikatortaste. Sie müssen abschaltbar, neu belegbar oder nur bei fokussierter Komponente aktiv sein.' },
    { id: 'focus-order', level: 'A', wcag: '2.4.3', title: 'Folgt der Fokus einer sinnvollen Reihenfolge?', summary: 'Die Reihenfolge erhält Bedeutung, Bedienbarkeit und erwartbare Wege.', test: 'Verfolge den Fokus durch die komplette Seite. Vermeide positive tabindex-Werte und DOM-/CSS-Widersprüche.' },
    { id: 'focus-visible', level: 'AA', wcag: '2.4.7', title: 'Ist der Tastaturfokus deutlich sichtbar?', summary: 'Jedes fokussierbare Element besitzt einen klar erkennbaren Fokusindikator.', test: 'Tabbe durch alle Zustände und Hintergründe. Entferne outline nur, wenn ein mindestens gleichwertiger eigener Fokus vorhanden ist.' },
    { id: 'focus-not-obscured', level: 'AA', wcag: '2.4.11', title: 'Wird der Fokus nicht vollständig verdeckt?', summary: 'Sticky Header, Cookie-Banner oder Overlays verdecken das aktive Element nicht vollständig.', test: 'Tabbe bei geöffneten persistenten Bannern und auf langen Seiten. Beobachte automatisch scrollende Fokuswechsel.' },
    { id: 'target-size', level: 'AA', wcag: '2.5.8', title: 'Sind kleine Klickziele ausreichend groß oder weit voneinander entfernt?', summary: 'Ziele sind grundsätzlich mindestens 24 × 24 CSS-px oder erfüllen die Abstands-Ausnahme.', test: 'Messe Iconbuttons, Pagination, Checkboxen und eng gesetzte Links. Inline-Textlinks und wesentliche Darstellungen besitzen Ausnahmen.' },
    { id: 'dragging', level: 'AA', wcag: '2.5.7', title: 'Gibt es eine Alternative zu Drag-and-drop?', summary: 'Funktionen mit Ziehbewegung lassen sich auch mit einfachem Zeiger bedienen.', test: 'Teste Sortierung, Slider, Karten und Uploadbereiche. Ergänze Buttons, Felder oder andere Einzelzeiger-Alternativen.' },
    { id: 'pointer-gestures', level: 'A', wcag: '2.5.1', title: 'Gibt es Alternativen für komplexe Zeigergesten?', summary: 'Mehrpunkt- und pfadbasierte Gesten lassen sich auch mit einem einzelnen Zeiger ausführen.', test: 'Prüfe Pinch-Zoom, Wischen, Zeichnen und Kartensteuerung. Biete Buttons oder eine einfache Einzelzeiger-Bedienung an, sofern die Geste nicht wesentlich ist.' },
    { id: 'pointer-cancellation', level: 'A', wcag: '2.5.2', title: 'Lassen sich versehentliche Zeigeraktionen vermeiden oder abbrechen?', summary: 'Aktionen werden möglichst beim Loslassen ausgelöst und können vor Abschluss abgebrochen oder rückgängig gemacht werden.', test: 'Drücke auf ein Bedienelement, bewege den Zeiger weg und lasse los. Kritische Down-Events brauchen eine sichere Abbruch- oder Rückgängig-Funktion.' },
    { id: 'label-name', level: 'A', wcag: '2.5.3', title: 'Kommt die sichtbare Beschriftung im zugänglichen Namen vor?', summary: 'Sprachsteuerung kann Elemente mit dem sichtbaren Text ansprechen.', test: 'Vergleiche sichtbaren Text und Accessible Name. Der sichtbare Wortlaut sollte möglichst am Anfang und unverändert enthalten sein.' },
    { id: 'link-purpose', level: 'A', wcag: '2.4.4', title: 'Ist der Zweck von Links im Kontext verständlich?', summary: 'Generische Texte wie „mehr“ sind nur mit eindeutig verbundenem Kontext zulässig.', test: 'Lass dir alle Links als Liste ausgeben. Gleichlautende Links zu verschiedenen Zielen brauchen unterscheidbare Namen.' },
    { id: 'motion-input', level: 'A', wcag: '2.5.4', title: 'Sind bewegungsbasierte Funktionen auch anders bedienbar?', summary: 'Schütteln, Neigen oder Gerätebewegung ist abschaltbar und besitzt eine Alternative.', test: 'Prüfe mobile Funktionen und Sensorinteraktionen. Bewegung darf nur bei wesentlicher Funktion die alleinige Methode sein.' }
  ]},
  { title: 'Formulare & Prozesse', kicker: 'Clear input, safe outcome', checks: [
    { id: 'labels', level: 'A', wcag: '1.3.1 / 3.3.2', title: 'Besitzen Eingabefelder dauerhafte, verständliche Beschriftungen?', summary: 'Label und Anleitung erklären erwartete Eingaben; Placeholder ersetzt kein Label.', test: 'Klicke auf Beschriftungen und prüfe Accessible Names. Pflichtstatus und Formatvorgaben müssen vor der Eingabe verständlich sein.' },
    { id: 'autocomplete', level: 'AA', wcag: '1.3.5', title: 'Sind bekannte persönliche Eingabezwecke programmatisch erkennbar?', summary: 'Geeignete autocomplete-Werte unterstützen automatisches Ausfüllen und Anpassungen.', test: 'Prüfe Felder für Name, Adresse, Telefon, E-Mail und Zahlungsdaten gegen die standardisierten autocomplete-Tokens.' },
    { id: 'errors', level: 'A/AA', wcag: '3.3.1 / 3.3.3', title: 'Werden Fehler eindeutig erkannt und erklärt?', summary: 'Fehler werden in Text benannt, dem Feld zugeordnet und mit Korrekturhinweisen ergänzt.', test: 'Sende leere und falsche Werte. Fokus, Zusammenfassung und Inline-Fehler müssen auffindbar sein; Farbe allein reicht nicht.' },
    { id: 'context-change', level: 'A', wcag: '3.2.1 / 3.2.2', title: 'Verursachen Fokus oder Eingabe keine unerwarteten Kontextwechsel?', summary: 'Das Fokussieren oder Ändern eines Feldes öffnet nicht überraschend neue Seiten, Fenster oder Prozesse.', test: 'Tabbe durch Felder und ändere Auswahlen. Automatisches Absenden oder Navigieren muss vorher erklärt sein oder erst durch eine bewusste Aktion erfolgen.' },
    { id: 'review', level: 'AA', wcag: '3.3.4', title: 'Können wichtige rechtliche oder finanzielle Eingaben geprüft werden?', summary: 'Nutzende können Angaben korrigieren, bestätigen oder Aktionen rückgängig machen.', test: 'Prüfe Käufe, Verträge, Zahlungen und Löschaktionen. Vor Abschluss muss eine sichere Kontrollmöglichkeit bestehen.' },
    { id: 'redundant-entry', level: 'A', wcag: '3.3.7', title: 'Müssen zuvor eingegebene Daten nicht unnötig erneut erfasst werden?', summary: 'Informationen im selben Prozess werden übernommen oder auswählbar angeboten.', test: 'Durchlaufe mehrstufige Formulare. Ausnahmen gelten unter anderem für Sicherheit, wesentliche Neueingabe oder veraltete Daten.' },
    { id: 'authentication', level: 'AA', wcag: '3.3.8', title: 'Funktioniert Anmeldung ohne kognitiven Funktionstest?', summary: 'Passwortmanager, Einfügen und geeignete Alternativen bleiben möglich.', test: 'Prüfe Login und Verifikation: Copy/Paste und Passwortmanager dürfen nicht blockiert sein. CAPTCHAs brauchen zugängliche Alternativen.', tip: 'Verlange keine selbst gelösten Rätsel oder auswendig gelernten Informationen, wenn kein unterstützender Mechanismus vorhanden ist.' },
    { id: 'status-messages', level: 'AA', wcag: '4.1.3', title: 'Werden dynamische Statusmeldungen assistiver Technik mitgeteilt?', summary: 'Erfolg, Fehler, Ladezustand und Ergebnisanzahl werden ohne Fokusverschiebung angekündigt.', test: 'Nutze einen Screenreader bei Suche, Warenkorb, Upload und Versand. Verwende passende Rollen oder Live-Regionen sparsam.' }
  ]},
  { title: 'Medien, Bewegung & Zeit', kicker: 'Control the experience', checks: [
    { id: 'captions', level: 'A', wcag: '1.2.2', title: 'Haben aufgezeichnete Videos synchronisierte Untertitel?', summary: 'Gesprochene Inhalte und relevante Geräusche sind zeitlich passend verfügbar.', test: 'Prüfe Vollständigkeit, Synchronität, Sprecherwechsel und wichtige Geräusche. Automatische Untertitel müssen redaktionell kontrolliert werden.' },
    { id: 'live-captions', level: 'AA', wcag: '1.2.4', title: 'Haben Liveübertragungen synchronisierte Untertitel?', summary: 'Gesprochene Inhalte und relevante Geräusche werden auch bei Live-Audio in Untertiteln vermittelt.', test: 'Prüfe Livestreams und Webveranstaltungen mit Ton. Plane ein geeignetes Verfahren und kontrolliere Verständlichkeit, Verzögerung und Sprecherzuordnung.' },
    { id: 'audio-description', level: 'AA', wcag: '1.2.5', title: 'Sind rein visuelle Videoinformationen auditiv zugänglich?', summary: 'Relevante Handlung, Text und visuelle Zusammenhänge werden per Audiodeskription vermittelt.', test: 'Höre das Video ohne Bild. Wenn relevante Information fehlt, ergänze Audiodeskription; bereits im Ton erklärte Bilder brauchen keine Dopplung.' },
    { id: 'audio-transcript', level: 'A', wcag: '1.2.1', title: 'Gibt es Alternativen für reine Audio- oder Videoinhalte?', summary: 'Aufzeichnungen ohne passende zweite Spur erhalten eine gleichwertige Alternative.', test: 'Prüfe Podcasts, Audiodateien und Videos ohne Ton. Ein Transkript muss alle relevanten Inhalte und Sprecherinformationen enthalten.' },
    { id: 'audio-control', level: 'A', wcag: '1.4.2', title: 'Ist automatisch abgespielter Ton kontrollierbar?', summary: 'Ton über drei Sekunden kann pausiert, gestoppt oder unabhängig geregelt werden.', test: 'Lade Seiten neu und prüfe Medien, Werbung und Hintergrundton. Am sichersten ist, Audio nicht ungefragt zu starten.' },
    { id: 'pause-motion', level: 'A', wcag: '2.2.2', title: 'Lassen sich automatisch bewegte oder aktualisierte Inhalte pausieren?', summary: 'Bewegung über fünf Sekunden sowie Auto-Updates sind stoppbar, ausblendbar oder steuerbar.', test: 'Prüfe Slider, Animationen, Ticker, Timer und Live-Daten. Wesentliche Prozessanzeigen können Ausnahmen besitzen.' },
    { id: 'flashing', level: 'A', wcag: '2.3.1', title: 'Vermeidet die Seite gefährliches Blitzen?', summary: 'Inhalte blitzen nicht häufiger als dreimal pro Sekunde oder bleiben unter den Grenzwerten.', test: 'Verwende bei blinkenden Medien ein geeignetes Analysewerkzeug. Eine visuelle Einschätzung reicht bei Grenzfällen nicht.', tip: 'Im Zweifel Blitzen vollständig vermeiden – besonders bei großflächigen, kontrastreichen Wechseln.' },
    { id: 'timeouts', level: 'A', wcag: '2.2.1', title: 'Sind Zeitbegrenzungen anpassbar oder vermeidbar?', summary: 'Nutzende können Zeitlimits abschalten, verlängern oder werden rechtzeitig gewarnt.', test: 'Prüfe Sessions, Formulare und Buchungen. Warnungen müssen genug Zeit zur Verlängerung geben; Echtzeitereignisse können ausgenommen sein.' },
    { id: 'reduced-motion', level: 'Best practice', wcag: '2.3.3 AAA', title: 'Respektiert die Oberfläche reduzierte Bewegungspräferenzen?', summary: 'Nicht wesentliche Interaktionsanimationen können deaktiviert oder reduziert werden.', test: 'Aktiviere prefers-reduced-motion im Betriebssystem und prüfe Übergänge, Parallax, Zoom und Scrollanimationen.' }
  ]},
  { title: 'Technik & Qualitätssicherung', kicker: 'Evidence over assumption', checks: [
    { id: 'name-role-value', level: 'A', wcag: '4.1.2', title: 'Haben Komponenten korrekte Namen, Rollen und Zustände?', summary: 'Assistive Technik erkennt Zweck und aktuellen Zustand aller Bedienelemente.', test: 'Prüfe native und benutzerdefinierte Widgets im Accessibility-Tree und mit Screenreader. expanded, selected und invalid müssen aktuell bleiben.' },
    { id: 'responsive-at', level: 'A/AA', wcag: 'mehrere', title: 'Wurden reale Browser und assistive Techniken getestet?', summary: 'Automatisierte Tools werden durch Tastatur-, Screenreader-, Zoom- und mobile Tests ergänzt.', test: 'Teste aktuelle Browser, nur Tastatur, starken Zoom und einen verbreiteten Screenreader. Dokumentiere Plattform und Version.' },
    { id: 'automation', level: 'Qualität', wcag: 'mehrere', title: 'Laufen automatisierte Prüfungen ohne kritische Befunde?', summary: 'Linting und Scanner finden einen Teil technischer Barrieren frühzeitig.', test: 'Nutze etwa axe, Lighthouse oder Pa11y. Prüfe Befunde manuell und behandle einen fehlerfreien Lauf nie als Konformitätsnachweis.', tip: 'Automatische Tests erkennen nur einen Teil der WCAG-Anforderungen und können Fehlalarme oder Barrieren übersehen.' },
    { id: 'content-states', level: 'Qualität', wcag: 'mehrere', title: 'Wurden alle Zustände und Seitentypen einbezogen?', summary: 'Fehler, leere Zustände, Overlays, eingeloggte Bereiche und dynamische Ergebnisse gehören zum Prüfumfang.', test: 'Erstelle eine repräsentative Stichprobe aus Templates, Kernprozessen, komplexen Komponenten und zufällig ausgewählten Seiten.' },
    { id: 'user-testing', level: 'Qualität', wcag: 'WCAG-EM', title: 'Wurden Menschen mit Behinderungen einbezogen?', summary: 'Reale Nutzung ergänzt die technische Prüfung und deckt praktische Barrieren auf.', test: 'Plane Aufgaben mit passenden Nutzergruppen, dokumentiere Beobachtungen und trenne Usability-Befunde von formaler WCAG-Bewertung.' },
    { id: 'statement', level: 'Qualität', wcag: 'WCAG-EM', title: 'Sind Prüfumfang, Methode und Ergebnis transparent dokumentiert?', summary: 'Aussagen nennen Standard, Level, Version, getestete Bereiche, Ausnahmen und Datum.', test: 'Vermeide pauschale Claims auf Basis einzelner Seiten oder Tools. Nutze für belastbare Evaluationen die Schritte der WCAG-EM.' }
  ]}
]
